name: Homebrew

on:
  push:
    tags: ["v*"]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Bump formula in tap
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: query-ts
          homebrew-tap: 1stvamp/homebrew-tap
          download-url: https://github.com/1stvamp/query-ts/archive/refs/tags/${{ github.ref_name }}.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
